apiVersion: v1
kind: Service
metadata:
  name:  a1-simulator
  labels:
    run: a1-simulator
spec:
  ports:
    - protocol: TCP
      port: 8085 # Port on the service
      targetPort: 8085 # Target port on the pod
  selector:
    run: a1-simulator
  type: ClusterIP