apiVersion: v1
kind: Pod
metadata:
  name: a1-simulator
  labels:
    run: a1-simulator
spec:
  containers:
  - name: a1-simulator
    image: armdocker.rnd.ericsson.se/proj-eric-oss-dev-test/a1-simulator
    ports:
    - containerPort: 8185
    env:
    - name: A1_VERSION
      value: "OSC_2.1.0"
    - name: ALLOW_HTTP
      value: "true"
  imagePullSecrets:
    - name: k8s-registry-secret