apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "eric-oss-oran-support.labels" . | nindent 4 }}
    app: os-k6
    sidecar.istio.io/inject: "true"
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
  volumes:
    - name: "{{ .Chart.Name }}-reports"
      emptyDir: {}
    - name: "{{ .Chart.Name }}-logs"
      emptyDir: {}
  containers:
    - name: "{{ $.Chart.Name }}"
      image: {{ $.Values.images.testwareImage | quote }}
      env:
        - name: A1_URL
          value: {{ $.Values.env.A1_URL }}
        - name: "APP_VERSION"
          value: "{{ include "get-application-version" $ | trim | default "undefined" }}"
        - name: "BUILD_URL"
          value: {{ $.Values.env.BUILD_URL }}
        - name: "STAGING_TYPE"
          value: {{ $.Values.env.STAGING_TYPE }}
        - name: "PRODUCT"
          value: {{ $.Values.env.PRODUCT }}
        - name: "PRODUCT_VERSION"
          value: "{{ include "get-product-version" $ | trim | default "undefined" }}"
        - name: "ENVIRONMENT"
          value: {{ $.Values.env.ENVIRONMENT }}
        - name: 'OPTIONS_FILE'
          value: '/resources/config/{{ $.Values.env.OPTIONS_FILE }}'
        - name: 'GAS_HOSTNAME_V'
          value: {{ $.Values.env.GAS_HOSTNAME }}
        - name: 'GAS_HOSTNAME_CM'
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "gas"
              optional: true
        - name: 'IAM_HOSTNAME_V'
          value: '{{ $.Values.env.IAM_HOSTNAME }}'
        - name: 'IAM_HOSTNAME_CM'
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "iam"
              optional: true
        - name: "EIC_HOSTNAME_V"
          value: {{ $.Values.env.EIC_HOSTNAME }}
        - name: "EIC_HOSTNAME_CM"
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "iam"
              optional: true
        - name: "SEF_STATUS_V"
          value: "{{ $.Values.env.SEF_STATUS }}"
        - name: "SEF_STATUS_CM"
          valueFrom:
            configMapKeyRef:
              name: testware-global-config
              key: "sef-enabled"
              optional: true
        - name: 'A1_VERSION'
          value: '{{ $.Values.env.A1_VERSION }}'
        - name: 'ALLOW_HTTP'
          value: '{{ $.Values.env.ALLOW_HTTP }}'
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: database_url
        - name: K6_TOOL_GUI_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: gui_url
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: api_url
      volumeMounts:
        - name: "{{ $.Chart.Name }}-reports"
          mountPath: "/reports"
        - name: "{{ .Chart.Name }}-logs"
          mountPath: "/var/log"
      imagePullPolicy: Always
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        runAsNonRoot: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: k8s-registry-secret
  schedulerName: default-scheduler
  restartPolicy: Never
  securityContext: {}
  terminationGracePeriodSeconds: 5