#The copyright to the computer program(s) herein is the property of
#Ericsson Inc. The programs may be used and/or copied only with written
#permission from Ericsson Inc. or in accordance with the terms and
#conditions stipulated in the agreement/contract under which the
#program(s) have been supplied.
apiVersion: v1
kind: Pod

metadata:
  name: os-k6-testsuite
  labels:
    app: os-k6
    sidecar.istio.io/inject: "true"
  annotations:
    proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
spec:
      containers:
        - name: os-k6
          env:
            - name: A1_URL
              value: "http://eric-oss-a1-policy-mgmt-svc:9080/"
            - name: K6_OUT
              value: "json=test-output.json"
            - name: BUILD_URL
              value: '%BUILD_URL%'
            - name: APP_VERSION
              value: '%APP_VERSION%'
            - name: GAS_HOSTNAME
              value: "%GAS_HOSTNAME%"
          image: armdocker.rnd.ericsson.se/proj-eric-oss-dev-test/eric-oss-oran-support-test:0.0.0
          volumeMounts:
          - name: dir-for-reports
            mountPath: '/reports'
          imagePullPolicy: Always
          resources: {}
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
      - name: dir-for-reports
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: k8s-registry-secret
      schedulerName: default-scheduler
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 10