kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: os-a1
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: eric-oss-a1-policy-mgmt-svc
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: os-k6
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-oran-support-app-engineering
  policyTypes:
    - Ingress
