kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: os-sim
spec:
  podSelector:
    matchLabels:
      run: a1-simulator
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: os-k6
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: eric-oss-oran-support-app-engineering
  policyTypes:
    - Ingress
